---

- name: Ensure Apache is deployed
  hosts: web_servers
  force_handlers: true
  gather_facts: false

  roles:
    - role: apache
      firewall_rules: "{{ lookup('ansible.builtin.template', 'apache_firewall_rules.yml.j2') | from_yaml }}"

