---
- name: sets persistent GRUB timeout
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: "^GRUB_TIMEOUT="
    line: "GRUB_TIMEOUT={{ grub_timeout | int }}"
  when: grub_persistent | bool == true

- name: sets temporary GRUB timeout
  ansible.builtin.lineinfile:
    path: /boot/grub2/grub.cfg
    regexp: "^set timeout="
    line: "set timeout={{ grub_timeout | int }}"
