---
version: 1

build_arg_defaults:
  EE_BASE_IMAGE: hub.lab.example.com/ee-minimal-rhel8:latest
  EE_BUILDER_IMAGE: hub.lab.example.com/ansible-builder-rhel8:latest
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-c"

ansible_config: ansible.cfg

dependencies:
  galaxy: requirements.yml
