---
- name: Upgrade Web Application
  hosts: web_servers
  become: true
  serial:
    - 5%
    - 35%
    - 100%
  max_fail_percentage: 0

  pre_tasks:
    - name: disable web servers in proxy
      delegate_to: "{{ groups['lb_servers'][0] }}"
      community.general.haproxy:
         state: disabled
         host: '{{ inventory_hostname }}'
         backend: app

  roles:
    - role: webapp

  post_tasks:
    - name: Smoke Test - Ensure HTTP 200 OK
      ansible.builtin.uri:
        url: "http://localhost:{{ apache_port }}"
        status_code: 200
      become: true
   
    - name: enable web servers in proxy
      delegate_to: "{{ groups['lb_servers'][0] }}"
      community.general.haproxy:
         state: enabled
         host: '{{ inventory_hostname }}'
         backend: app
